# SPDX-License-Identifier: GPL-2.0-or-later
# MonoidalCategories: Monoidal and monoidal (co)closed categories
#
# Declarations
#
# THIS FILE IS AUTOMATICALLY GENERATED, SEE CAP_project/CAP/gap/MethodRecordTools.gi

#! @Chapter Monoidal Categories

#! @Section Add-methods

#! @BeginGroup
#! @Description
#! The arguments are a category $C$ and a function $F$.
#! This operation adds the given function $F$
#! to the category for the basic operation `TensorProductOnListOfMorphisms`.
#! Optionally, a weight (default: 100) can be specified which should roughly correspond
#! to the computational complexity of the function (lower weight = less complex = faster execution).
#! $F: ( list_of_mors ) \mapsto \mathtt{TensorProductOnListOfMorphisms}(list_of_mors)$.
#! @Returns nothing
#! @Arguments C, F
DeclareOperation( "AddTensorProductOnListOfMorphisms",
                  [ IsCapCategory, IsFunction ] );

#! @Arguments C, F, weight
DeclareOperation( "AddTensorProductOnListOfMorphisms",
                  [ IsCapCategory, IsFunction, IsInt ] );
#! @EndGroup


#! @BeginGroup
#! @Description
#! The arguments are a category $C$ and a function $F$.
#! This operation adds the given function $F$
#! to the category for the basic operation `TensorProductOnListOfMorphismsWithGivenTensorProducts`.
#! Optionally, a weight (default: 100) can be specified which should roughly correspond
#! to the computational complexity of the function (lower weight = less complex = faster execution).
#! $F: ( s, list_of_mors, r ) \mapsto \mathtt{TensorProductOnListOfMorphismsWithGivenTensorProducts}(s, list_of_mors, r)$.
#! @Returns nothing
#! @Arguments C, F
DeclareOperation( "AddTensorProductOnListOfMorphismsWithGivenTensorProducts",
                  [ IsCapCategory, IsFunction ] );

#! @Arguments C, F, weight
DeclareOperation( "AddTensorProductOnListOfMorphismsWithGivenTensorProducts",
                  [ IsCapCategory, IsFunction, IsInt ] );
#! @EndGroup


#! @BeginGroup
#! @Description
#! The arguments are a category $C$ and a function $F$.
#! This operation adds the given function $F$
#! to the category for the basic operation `TensorProductOnListOfObjects`.
#! Optionally, a weight (default: 100) can be specified which should roughly correspond
#! to the computational complexity of the function (lower weight = less complex = faster execution).
#! $F: ( arg2 ) \mapsto \mathtt{TensorProductOnListOfObjects}(arg2)$.
#! @Returns nothing
#! @Arguments C, F
DeclareOperation( "AddTensorProductOnListOfObjects",
                  [ IsCapCategory, IsFunction ] );

#! @Arguments C, F, weight
DeclareOperation( "AddTensorProductOnListOfObjects",
                  [ IsCapCategory, IsFunction, IsInt ] );
#! @EndGroup

